"use client";import {useState} from 'react';import {Badge,EmptyState,ErrorState,Progress} from './ui';
export const Panel=({children}:{children:React.ReactNode})=><section className="card">{children}</section>;
export const Tabs=({items,active,onChange}:{items:string[];active:string;onChange:(v:string)=>void})=><div className="filters" role="tablist">{items.map(x=><button role="tab" aria-selected={active===x} className={`btn ${active===x?'primary':''}`} onClick={()=>onChange(x)} key={x}>{x}</button>)}</div>;
export const Input=(p:React.InputHTMLAttributes<HTMLInputElement>)=><input {...p} className={`input ${p.className||''}`}/>;
export const Textarea=(p:React.TextareaHTMLAttributes<HTMLTextAreaElement>)=><textarea {...p} className={`input ${p.className||''}`}/>;
export const Select=(p:React.SelectHTMLAttributes<HTMLSelectElement>)=><select {...p} className={`input ${p.className||''}`}/>;
export const Avatar=({name}:{name:string})=><span className="avatar" aria-label={name}>{name.slice(0,1).toUpperCase()}</span>;
export function Tooltip({label,children}:{label:string;children:React.ReactNode}){return <span title={label}>{children}</span>}
export function Dropdown({label,items}:{label:string;items:string[]}){const [open,setOpen]=useState(false);return <div style={{position:'relative'}}><button className="btn" onClick={()=>setOpen(!open)}>{label} ▾</button>{open&&<div className="card" style={{position:'absolute',top:'calc(100% + 4px)',right:0,zIndex:20,minWidth:150,padding:6}}>{items.map(x=><button className="nav" key={x} onClick={()=>setOpen(false)}>{x}</button>)}</div>}</div>}
export function Modal({open,title,children,onClose}:{open:boolean;title:string;children:React.ReactNode;onClose:()=>void}){if(!open)return null;return <div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:50,background:'#0009',display:'grid',placeItems:'center',padding:20}}><div className="card" style={{width:'min(640px,100%)'}}><div className="titleRow"><h3>{title}</h3><button className="btn" onClick={onClose} aria-label="Close">×</button></div>{children}</div></div>}
export function ConfirmDialog({open,title,body,onConfirm,onCancel}:{open:boolean;title:string;body:string;onConfirm:()=>void;onCancel:()=>void}){return <Modal open={open} title={title} onClose={onCancel}><p className="sub">{body}</p><div className="actions" style={{marginTop:14}}><button className="btn" onClick={onCancel}>Cancel</button><button className="btn primary" onClick={onConfirm}>Confirm</button></div></Modal>}
export const StatusIndicator=({status}:{status:string})=><Badge type={status==='FAILED'||status==='REJECTED'?'danger':status==='READY_FOR_REVIEW'||status==='REVIEW'?'warning':status==='PROCESSING'||status==='RUNNING'?'processing':status==='APPROVED'||status==='SUCCEEDED'?'success':'pending'}>{status}</Badge>;
export const DataTable=({children}:{children:React.ReactNode})=><div style={{overflowX:'auto'}}>{children}</div>;
export const AudioPlayer=({duration='03:42'}:{duration?:string})=><div><div className="wave"/><div className="actions" style={{marginTop:8}}><button className="btn">▶ Play</button><button className="btn">Restart</button><span className="label">00:00 / {duration}</span></div></div>;
export const VideoPlayer=({label='Video preview'}:{label?:string})=><div className="preview" aria-label={label}>{label}</div>;
export const Timeline=({children}:{children?:React.ReactNode})=><div className="timeline timelineLarge">{children||<div className="label">Declarative timeline</div>}</div>;
export const SceneCard=({number,narration,status}:{number:number;narration:string;status:string})=><div className="card"><div className="sceneTop"><span className="sceneNum">Scene {String(number).padStart(2,'0')}</span><StatusIndicator status={status}/></div><div className="sceneText">{narration}</div></div>;
export const AssetCard=({name,type,status}:{name:string;type:string;status:string})=><div className="card"><div className="candidatePreview">{type}</div><b>{name}</b><div style={{marginTop:8}}><StatusIndicator status={status}/></div></div>;
export const ApprovalCard=({stage,status}:{stage:string;status:string})=><div className="card approval"><div className="label">APPROVAL</div><h3>{stage}</h3><StatusIndicator status={status}/></div>;
export const JobStatus=({status,progress}:{status:string;progress?:number})=><div><StatusIndicator status={status}/>{typeof progress==='number'&&<div style={{marginTop:8}}><Progress value={progress}/></div>}</div>;
export {Badge,EmptyState,ErrorState,Progress};
