import { JobType, Prisma, PublicationStatus } from "@prisma/client";
import { prisma } from "../db/prisma.js";
import { jobService } from "../services/job-service.js";
import { pipelineService } from "../services/pipeline-service.js";
import { MockLLMProvider, MockResearchProvider } from "../providers/mock/mock-providers.js";
import { MockPublishingProvider, MockVoiceProvider } from "../providers/mock/media-providers.js";
const llm=new MockLLMProvider(),researchProvider=new MockResearchProvider(),voiceProvider=new MockVoiceProvider(),publishingProvider=new MockPublishingProvider();
type Job=Awaited<ReturnType<typeof prisma.job.findUnique>>;
export async function handleJob(job:NonNullable<Job>){if(!job.projectId)throw new Error(`Job ${job.id} has no project.`);const projectId=job.projectId,payload=(job.payload??{}) as Record<string,any>;switch(job.type){
case JobType.RESEARCH:{const p=await prisma.project.findUniqueOrThrow({where:{id:projectId}});const s=await researchProvider.search(p.topic),r=await Promise.all(s.map(x=>researchProvider.retrieve(x.url)));return pipelineService.research(projectId,{...(await researchProvider.analyze({topic:p.topic,sources:r})),sources:r});}
case JobType.GENERATE_BRIEF:{const p=await prisma.project.findUniqueOrThrow({where:{id:projectId},include:{research:true}}),g=await llm.generateStructuredOutput<any>({prompt:`Create a concise YouTube content brief for ${p.topic}. Research: ${JSON.stringify(p.research)}`,schema:{}}),o=g.output;return pipelineService.brief(projectId,{title:o.title??p.topic,hook:o.hook??`What you need to know about ${p.topic}`,promise:o.promise??`A clear explanation of ${p.topic}`,audience:o.audience??"general viewers",structure:o.structure??{sections:["Hook","Context","Key points","Conclusion"]}});}
case JobType.GENERATE_SCRIPT:{const p=await prisma.project.findUniqueOrThrow({where:{id:projectId},include:{contentBrief:true}}),g=await llm.generateText({prompt:`Write a YouTube script for ${p.topic}. Brief: ${JSON.stringify(p.contentBrief)}`,language:p.targetLanguage});return pipelineService.script(projectId,{title:p.contentBrief?.title??p.topic,language:p.targetLanguage,body:g.text,targetDurationSec:p.targetDurationSec??undefined});}
case JobType.BREAKDOWN_SCENES:{const s=await prisma.script.findUniqueOrThrow({where:{id:payload.scriptId}}),c=s.body.split(/(?<=[.!?])\s+/).filter(Boolean);return pipelineService.scenes(projectId,s.id,(c.length?c:[s.body]).map((n,i)=>({sceneNumber:i+1,title:`Scene ${i+1}`,narration:n,durationMs:Math.max(2000,Math.ceil(n.split(/\s+/).length*450)),imagePrompt:`Cinematic visual illustrating: ${n.slice(0,300)}`,videoPrompt:`Subtle motion for: ${n.slice(0,300)}`,motionPrompt:`Text emphasis for scene ${i+1}`})));}
case JobType.GENERATE_VOICEOVER:{const s=await prisma.script.findFirstOrThrow({where:{projectId},orderBy:{version:"desc"}}),g=await voiceProvider.synthesize({text:s.body,language:s.language});return pipelineService.voiceover(projectId,g.transcript,g.durationMs,g.audioStorageKey);}
case JobType.GENERATE_VISUAL:return pipelineService.visuals(projectId);
case JobType.GENERATE_MOTION:return pipelineService.motion(projectId);
case JobType.BUILD_TIMELINE:return pipelineService.timeline(projectId);
case JobType.RENDER:{const r=await pipelineService.render(projectId,payload.timelineId);return jobService.enqueueJob({projectId,type:JobType.QA,payload:{projectId,renderId:r.id},idempotencyKey:`pipeline:${projectId}:qa:${r.id}`});}
case JobType.GENERATE_METADATA:{const version=((await prisma.videoMetadata.findFirst({where:{projectId},orderBy:{version:"desc"}}))?.version??0)+1;return prisma.videoMetadata.create({data:{projectId,version,title:payload.title??"TubeGen Video",description:payload.description??"",tags:(payload.tags??[]) as Prisma.InputJsonValue,status:"APPROVED"}});}
case JobType.GENERATE_THUMBNAIL:{const version=((await prisma.thumbnail.findFirst({where:{projectId},orderBy:{version:"desc"}}))?.version??0)+1;return prisma.thumbnail.create({data:{projectId,version,titleText:payload.title??"TubeGen",status:"APPROVED"}});}
case JobType.QA:{const p=await prisma.project.findUniqueOrThrow({where:{id:projectId},include:{scenes:true,renders:{orderBy:{version:"desc"},take:1}}}),passed=p.scenes.length>0&&p.renders.length>0&&p.renders[0].status==="SUCCEEDED";if(!passed){await prisma.project.update({where:{id:projectId},data:{status:"FAILED",currentStage:"QA"}});return{passed,checks:{hasScenes:p.scenes.length>0,hasRender:p.renders.length>0}}}await prisma.project.update({where:{id:projectId},data:{status:"READY",currentStage:"APPROVAL"}});const m=await jobService.enqueueJob({projectId,type:JobType.GENERATE_METADATA,payload:{projectId},idempotencyKey:`pipeline:${projectId}:metadata`}),t=await jobService.enqueueJob({projectId,type:JobType.GENERATE_THUMBNAIL,payload:{projectId},idempotencyKey:`pipeline:${projectId}:thumbnail`});return{passed:true,metadataJobId:m.id,thumbnailJobId:t.id};}
case JobType.YOUTUBE_UPLOAD:{const pub=await prisma.publication.findUniqueOrThrow({where:{id:payload.publicationId}}),r=await prisma.render.findUniqueOrThrow({where:{id:payload.renderId}});if(!r.storageKey)throw new Error("Render has no storage key.");const u=await publishingProvider.upload({title:payload.title,description:payload.description,storageKey:r.storageKey,visibility:payload.visibility});return prisma.publication.update({where:{id:pub.id},data:{externalVideoId:u.externalVideoId,status:PublicationStatus.PUBLISHED,publishedAt:new Date(),responseData:u.responseData as Prisma.InputJsonValue}});}
default:throw new Error(`No handler registered for ${job.type}`);}}
export async function processOneJob(){const job=await jobService.claimJob();if(!job)return false;try{await jobService.succeedJob(job.id,(await handleJob(job)) as Prisma.InputJsonValue)}catch(e){await jobService.retryJob(job.id,e instanceof Error?e.message:String(e))}return true}
